### ISSUE TITLE
Different code for "Setup IMAP Integration"

### ISSUE THREAD

**Issue by binoke** [yohaybn/HA_aliexpress_package_tracker_sensor#3]
I tried to "Setup IMAP Integration" but noticed it did not allow me based on the example code.
I had to make these changes.
```
# configuration.yaml
template:
  - sensor:
	- trigger:
	  - trigger: event
        event_type: "imap_content"
        id: "custom_event"
        event_data:
          custom: true # See example here [https://www.home-assistant.io/integrations/imap/#example---custom-event-data-template](https://www.home-assistant.io/integrations/imap/#example---custom-event-data-template) how to set it up
      sensor:
        - name: post_track
          state: "{{ trigger.event.data['subject'] }}"
          attributes:
            body: "{{ trigger.event.data['text'] }}"
```
